In [1]:
import pandas as pd
import numpy as np

In [6]:
df_store = pd.read_csv("store.csv")
df_store.head(20)

,STT,Tên CH,Demand,Time start,Time end,Vĩ độ (Latitude),Kinh độ (Longitude)
0,1,MC-8 Thạch Lam,"111,640",10:00,10:30,10.776312,106.633415
1,2,BB-97 Tân Quý,"124,173",10:20,10:50,10.796304,106.620237
2,3,BB-252 Tân Hương,"88,175",10:20,10:50,10.790246,106.621155
3,4,MC-38 Trịnh Đình Trọng,"122,640",10:40,11:10,10.775470,106.646957
4,5,BB-8 Thạch Lam,"95,315",10:00,10:30,10.799971,106.616229
5,6,MC-111 Lê Trọng Tấn,"74,620",11:40,12:10,10.805951,106.629822
6,7,MC-182 Tân Sơn Nhì,"59,028",10:00,10:30,10.799474,106.632170
7,8,MC-5A Thích Quảng Đức,"111,690",12:20,12:50,10.804290,106.683593
8,9,MC-128 Phổ Quang,"54,928",11:40,12:10,10.808396,106.671739
9,10,BB-388A Cách Mạng Tháng Tám,"137,700",11:20,11:50,10.783068,106.672064
10,11,BB-279 Nguyễn Thái Sơn,"301,328",12:40,13:10,10.827741,106.690673
11,12,BB-112 Nguyễn Văn Nghi,"55,083",14:00,14:30,10.824348,106.686180
12,13,MC-122 Lê Văn Thọ,"52,230",14:20,14:50,10.840573,106.657414
13,14,MC-390 Phan Huy Ích,"61,300",14:40,15:10,10.841722,106.639098
14,15,MC-41 Nguyễn Văn Nghi,"97,775",13:00,13:30,10.824446,106.686591
15,16,BB-351 Tỉnh Lộ 10,"151,850",10:30,11:00,10.756537,106.622851
16,17,BB-847 Tỉnh Lộ 10,"123,780",10:50,11:20,10.758267,106.607097
17,18,BB-31 Đồng Đen,"205,240",10:50,11:20,10.794978,106.645300
18,19,BB-6 Hoàng Hoa Thám,"135,085",10:30,11:00,10.803961,106.692181
19,20,MC-161 Đường Số 1,"81,550",11:50,12:20,10.748347,106.617113

In [7]:
df_matrix = pd.read_csv("distant_matrix.csv")
df_matrix = df_matrix.drop(columns=['From/to'])
df_matrix.head(20)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.00,6.34,7.68,7.07,7.25,7.95,9.04,8.48,12.37,11.76,...,14.75,14.14,13.81,13.12,14.17,3.90,3.21,8.78,13.06,2.81
1,6.34,0.00,2.65,2.05,1.48,3.23,3.32,2.58,6.30,5.50,...,8.47,7.86,7.61,7.30,7.90,2.48,3.51,2.45,7.12,3.58
2,7.68,2.65,0.00,0.68,3.73,0.60,1.50,1.35,6.98,5.78,...,8.45,7.85,6.38,5.45,7.89,4.43,4.47,2.74,7.90,5.34
3,7.07,2.05,0.68,0.00,3.26,1.21,1.99,1.58,7.00,5.88,...,8.66,8.05,6.86,6.05,8.10,3.75,3.87,2.69,7.91,4.68
4,7.25,1.48,3.73,3.26,0.00,4.32,3.87,3.12,5.13,4.55,...,7.52,6.92,7.33,7.42,6.96,3.37,4.76,2.18,5.87,4.44
5,7.95,3.23,0.60,1.21,4.32,0.00,1.63,1.74,7.37,6.13,...,8.70,8.11,6.37,5.27,8.15,4.88,4.74,3.22,8.31,5.74
6,9.04,3.32,1.50,1.99,3.87,1.63,0.00,0.76,5.88,4.59,...,7.07,6.49,4.89,4.10,6.53,5.55,5.85,2.08,6.81,6.55
7,8.48,2.58,1.35,1.58,3.12,1.74,0.76,0.00,5.64,4.43,...,7.12,6.52,5.34,4.76,6.56,4.88,5.34,1.52,6.57,5.92
8,12.37,6.30,6.98,7.00,5.13,7.37,5.88,5.64,0.00,1.37,...,2.72,2.25,4.94,6.40,2.27,8.50,9.80,4.31,0.94,9.56
9,11.76,5.50,5.78,5.88,4.55,6.13,4.59,4.43,1.37,0.00,...,2.98,2.37,3.91,5.14,2.41,7.86,9.00,3.25,2.29,8.95
10,9.90,4.29,5.85,5.62,2.87,6.38,5.27,4.72,2.67,2.82,...,5.37,4.84,6.59,7.45,4.87,6.13,7.61,3.21,3.20,7.14
11,14.75,8.47,8.45,8.66,7.52,8.70,7.07,7.12,2.72,2.98,...,0.00,0.62,3.90,5.84,0.58,10.84,11.96,6.15,2.65,11.94
12,14.14,7.86,7.85,8.05,6.92,8.11,6.49,6.52,2.25,2.37,...,0.62,0.00,3.62,5.49,0.05,10.23,11.34,5.53,2.36,11.33
13,13.81,7.61,6.38,6.86,7.33,6.37,4.89,5.34,4.94,3.91,...,3.90,3.62,0.00,2.00,3.66,10.08,10.68,5.24,5.57,11.16
14,13.12,7.30,5.45,6.05,7.42,5.27,4.10,4.76,6.40,5.14,...,5.84,5.49,2.00,0.00,5.53,9.64,9.92,5.24,7.16,10.66
15,14.17,7.90,7.89,8.10,6.96,8.15,6.53,6.56,2.27,2.41,...,0.58,0.05,3.66,5.53,0.00,10.27,11.38,5.57,2.36,11.37
16,3.90,2.48,4.43,3.75,3.37,4.88,5.55,4.88,8.50,7.86,...,10.84,10.23,10.08,9.64,10.27,0.00,1.73,4.93,9.23,1.11
17,3.21,3.51,4.47,3.87,4.76,4.74,5.85,5.34,9.80,9.00,...,11.96,11.34,10.68,9.92,11.38,1.73,0.00,5.84,10.59,1.55
18,8.78,2.45,2.74,2.69,2.18,3.22,2.08,1.52,4.31,3.25,...,6.15,5.53,5.24,5.24,5.57,4.93,5.84,0.00,5.22,6.03
19,13.06,7.12,7.90,7.91,5.87,8.31,6.81,6.57,0.94,2.29,...,2.65,2.36,5.57,7.16,2.36,9.23,10.59,5.22,0.00,10.27

In [ ]:
cost_per_km = 18000
number_vehicels = 13
capacity = 1800 #1.8 tấn đổi ra kg